version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  celery-worker:
    build: .
    depends_on: 
      - rabbitmq
    entrypoint: ["celery", "-A", "app", "worker"]
    #entrypoint: ["scalene" "...", "...", "celery", "-A", "app", "worker"]
    # or... 
    # 1. ["sleep", "1000000"] 
    # 2. docker exec -it <image-name> bash; 
    # 3. run the scalene command while submitting tasks
    # 4. ^C it and get the report out.

  celery-taskgen:
    build: .
    ports:
      - 5000:5000
    depends_on: 
      - rabbitmq
    entrypoint: ["python3", "mktask.py"]
