version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  celery-worker:
    build: .
    depends_on: 
      - rabbitmq
    entrypoint: ["celery", "-A", "app", "worker"]

  celery-taskgen:
    build: .
    ports:
      - 5000:5000
    depends_on: 
      - rabbitmq
    environment: 
      - FLASK_APP=mktask
    entrypoint: ["flask", "run"]
